### PR TITLE
Tab Bar

### PR DESCRIPTION
**Pull request by pavsidhu**
- Added /me and /insight pages
- Tab bar
- Emoji SVGs

localhost_3000_me(iPhone 6_7_8) (2)

### CODE REVIEW

**Comment by adamjhc** [comment]
If we're using `/src/assets/` now instead of `/public` do you wanna move the rest into there too?

**Comment by pavsidhu** [comment]
According to next.js /public is for static files so images, videos etc, but we're loading in SVGs as React components so they're not static assets so it doesn't make sense to put them in /public, maybe there's a better name than /src/assets?

**Comment by adamjhc** [comment]
I'll open another pr for moving the other SVGs over then

**Comment by adamjhc** [comment]
Approved!

**Review by adamjhc — APPROVED** [review]

**Pull request merged**
